AP/IB page
BobaTalks/survival-guide pull request #38
Opened 2023-08-08 20:53 UTC by oo-ng

## Description
#### What is the purpose of your change?
I worked on the AP vs IB vs College classes

#### What areas of the application does this change impact? (changes API, folder structure, etc)
page

#### What features/fixes are deferred/not handled in this PR?
i believe everything was handled, i asked some questions about the format but i haven't gotten any feedback, i will be awaiting feedback if you need anything changed.

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

2023-08-15 20:27 UTC, michachan requested changes

2023-08-15 20:27 UTC, michachan commented on src/App.css
> +li {
As mentioned earlier, I can approve this now, but let's look for more scalable and consistent styling solutions. We'll need to refactor this vanilla CSS to another UI library- top ones to consider may be tailwind, material UI, chakra UI, and mantine

2023-08-15 20:27 UTC, michachan commented on src/App.css
> +  margin-right: 46px; */
remove commented/unused code

2023-08-15 20:27 UTC, michachan commented on src/App.js
> +                have been administered by the College Board. Which means by
nit, why not multiple <p> containers instead of double line breaks?

2023-08-15 20:27 UTC, michachan commented on src/MainBox.js
> +  // eslint-disable-next-line prettier/prettier
why are these prettier disable rules here?

2023-08-30 23:51 UTC, oo-ng commented
I apologize for the late update, I was struggling with pushing the updates to github.

2023-08-31 06:45 UTC, michachan commented on public/index.html
> +    <title>BoBaTalks</title>
check casing

2023-09-12 04:48 UTC, michachan approved these changes

2023-09-30 18:37 UTC, merged