Feature/faq
BobaTalks/survival-guide pull request #42
Opened 2023-09-21 16:21 UTC by aayusha-shrestha

## Description
#### What is the purpose of your change?
-Developed FAQ page

#### What areas of the application does this change impact? (changes API, folder structure, etc)
-FAQ section

#### What features/fixes are deferred/not handled in this PR?
-Responsive design

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

2023-09-30 18:38 UTC, michachan commented on src/pages/faq/Faq.js
> +    setClicked(id);
nit: alternatively, setClicked(() => clicked === id ? null : id)

2023-09-30 18:39 UTC, michachan commented on src/pages/faq/Faq.js
> +                    <div dangerouslySetInnerHTML={{ __html: faq.body }} />
why use dangerouslysetinnerhtml?

2023-09-30 18:39 UTC, michachan requested changes
Please explain reason why dangerouslysetinnerhtml is needed

2023-10-03 03:07 UTC, aayusha-shrestha commented
Thank you. Edited.

On Sun, 1 Oct 2023 at 12:23 AM Michael Chan ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/pages/faq/Faq.js
> <https://github.com/BobaTalks/survival-guide/pull/42#discussion_r1341996478>
> :
>
> > @@ -0,0 +1,51 @@
> +import { faChevronDown, faChevronUp } from ***@***.***/free-solid-svg-icons";
> +import { FontAwesomeIcon } from ***@***.***/react-fontawesome";
> +import { useState } from "react";
> +import catFaq from "../../images/catFaq.png";
> +import "./Faq.css";
> +import { faqs } from "./faqs";
> +
> +const Faq = () => {
> +  const [clicked, setClicked] = useState(false);
> +
> +  const toggle = (id) => {
> +    if (clicked === id) {
> +      return setClicked(null);
> +    }
> +    setClicked(id);
>
> nit: alternatively, setClicked(() => clicked === id ? null : id)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BobaTalks/survival-guide/pull/42#pullrequestreview-1651735475>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4BEY5PQU5346L5SW5G5D53X5BRLNANCNFSM6AAAAAA5BZ7JFQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-05 09:08 UTC, aayusha-shrestha commented
I apologize for my delayed response. A link needs to be attached to one of
the FAQs. I could not find any alternative to place the anchor tag in the
array.

On Sun, Oct 1, 2023 at 12:24 AM Michael Chan ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please explain reason why dangerouslysetinnerhtml is needed
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BobaTalks/survival-guide/pull/42#pullrequestreview-1651735584>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4BEY5OKOLK64ZRHJPKEKWLX5BRPHANCNFSM6AAAAAA5BZ7JFQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-05 10:02 UTC, aayusha-shrestha commented on src/pages/faq/Faq.js
> +    setClicked(id);
Re-render error occured

2024-01-19 07:14 UTC, michachan approved these changes

2024-01-19 07:15 UTC, merged